[package]
name = "rust-nn"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror="1.0.32"
rand="0.8.5"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.85"
plotters = "0.3"
macroquad = "0.3"
rayon="1.5.3"